### ISSUE TITLE
PureDNS never managed to resolve anything

### ISSUE THREAD

**Issue by hitem** [d3mondev/puredns#34]
Hello,
Maybe im doing something wrong here, but im unable to get this to work.
I wrote my own python request tool but its no way near as fast as pureDNS so i would love to get this one to work :).

```puredns resolve url_list.txt --write valid.txt -l 5```
this is the command i run, the ```resolvers.txt``` has ```8.8.8.8```, ```8.8.4.4``` and ```1.1.1.1``` in it.
![bild](https://user-images.githubusercontent.com/8977898/202301116-377880aa-558e-4ebf-addf-c6aa5e9e88c1.png)
Edit: My ```url_list.txt``` contains amass/subfinder enums, in the format: subdomain.domain.com (example.com, bob.example.com). I tried adding http and https etc infront but same with or without.

The ```valid.txt``` always comes back as empty, never get any resolves.
I am able to resolve domains with httpx and my own tool, but not with pureDNS. Anyone been in a similiar pickle and managed to resolve it ? (lol!).
MassDNS is installed to but i have not done anything with it (using kali out the box distro).

Would be greatly appreciated.

**Comment by d3mondev** [comment]
Puredns will filter out invalid domains by default. If I understand correctly, your url_list.txt file contains lines looking like this:

```
subdomain.domain.com (example.com, bob.example.com)
```

That line will get discarded because `(` and `,` are not valid characters in a domain name. Try to parse your list to produce only the domain names to resolve, one per line.

Also, I don't use Kali but make sure massdns is up to date.
